version: '0.1'

services:
  carla-server:
    image: carlasim/carla:0.9.13
    privileged: true
    user: 1001:1001
    networks:
      - carla-network
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/recordings:/tmp/recordings:rw
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: /bin/bash ./CarlaUE4.sh -RenderOffScreen -quality-level=Low

  carla-client:
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
      - CARLA_ROOT=/opt/CARLA/Simulator
      - PYTHONPATH=/opt/OpenSBT/Runner:/opt/CARLA/Simulator/PythonAPI/carla/dist/carla-0.9.13-py3.7-linux-x86_64.egg:/opt/CARLA/Simulator/PythonAPI/carla/agents:/opt/CARLA/Simulator/PythonAPI/carla:/opt/CARLA/Runner
      - SCENARIO_RUNNER_ROOT=/opt/CARLA/Runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/recordings:/tmp/recordings:rw
      - ${ROSCO_PATH}:/opt/workspace/src/rosco:rw
      - ${SHARE_PATH}:/opt/workspace/share:rw
      - ${CARLA_PATH}:/opt/CARLA/Simulator:r
      - ${SCENARIORUNNER_PATH}:/opt/CARLA/Runner:r
      - ${OPENSBT_CORE_PATH}:/opt/OpenSBT/Core:rw
      - ${OPENSBT_RUNNER_PATH}:/opt/OpenSBT/Runner:rw
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: "host"
    ipc: host
    command: sleep infinity
    depends_on:
      - carla-server

networks:
  carla-network:
   name: carla-network
