version: '0.1'

services:
  carla-server:
    image: carlasim/carla:0.9.13
    privileged: true
    user: 1001:1001
    networks:
      - carla-network
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/recordings:/tmp/recordings:rw
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: /bin/bash ./CarlaUE4.sh -RenderOffScreen -quality-level=Low
    
  carla-client:
    image: client-rosco
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #path to rosco repo
      - /home/pavel/Documents/bachelorarbeit/workspace/src/rosco:/opt/workspace/src/rosco:rw
      #path to FMUs that should be executed by rosco
      - /home/pavel/Documents/bachelorarbeit/workspace/src/rosco/share:/opt/workspace/share:rw
      #path to the carla simulation repo
      - /home/pavel/Documents/bachelorarbeit/CARLA:/opt/CARLA/:r
      #path to the carla scenario runner repo
      - /home/pavel/Documents/bachelorarbeit/scenario_runner:/opt/scenario_runner/:r
      - /tmp/recordings:/tmp/recordings:rw
    network_mode: "host"
    command: /bin/bash
    tty: true
    stdin_open: true

networks:
  carla-network:
   name: carla-network
